syntax = "proto3";

package final_data_cleaning_control_bi_stream;

// 计算任务指令
message ComputeTask {
    // 任务唯一标识
    string task_id = 1;
    // 需要计算的 SessionId，未来支持线程池复用后可以传个数组
    string session_id = 2;
    // 需要计算的日期
    string date = 3;
}

// 进度更新指令
message ProgressUpdate {
    // 关联的任务ID
    string task_id = 1;
    // 进度百分比（0-100）
    int32 progress = 2;
    // 节点唯一标识
    string node_id = 3;
    // 附加信息（如“正在处理第3个分片”）
    string message = 4;
    // 是否完成
    bool completed = 5;
    // 是否失败
    bool failed = 6;
    // 失败信息
    string error = 7;
}

// 计算服务
service ComputeService {
    // 双向流
    rpc TaskStream (stream ComputeTask) returns (stream ProgressUpdate);
}

// 节点信息查询指令
message GetNodeInfoRequest {
}

// 节点信息
message NodeInfo {
    // cpu核心数
    int32 cpu_count = 1;
    // 总内存大小，MB单位
    int32 memory_size = 2;
    // 可用内存大小，MB单位
    int32 available_memory_size = 3;
    // 是否可用
    bool available = 4;
    // 是否忙碌中
    bool busy = 5;
    // 忙碌任务id
    string busy_task_id = 6;
}

// 节点信息查询服务
service NodeInfoService {
    rpc GetNodeInfo (GetNodeInfoRequest) returns (NodeInfo);
}